 name : GitActions
 on :
  push :
    branches : [ master ]
  pull_request :
    branches : [ master ]
 jobs :
  build :
    runs-on : ubuntu-latest
    steps :
      - name: Checkout the code
        uses: actions/checkout@v4.1.1

      - name : Setup Java JDK
        uses : actions/setup-java@v3.13.0
        with :
        java_version : '17'

      - name : Build with Gradle
        run : .gradlew/ build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0

        with:
          name: AndroidCICI.apk
          path: app/build/outputs/apk/app-debug.apk